### ISSUE TITLE
所有的参数控制完全兼容吗？

### ISSUE THREAD

**Issue by shaoyuyoung** [Slinet6056/OpenAnakin#1]
你好
请问这个参数它完全支持openai的所有控制参数吗？
比如temperature，top_p？

**Comment by Slinet6056** [comment]
不支持的，那些参数只能在anakin创建应用的时候设置好

**Comment by shaoyuyoung** [comment]
那对于`终止符（END_OF_STRING）`也许可以通过流式处理来实现？

**Comment by Slinet6056** [comment]
不是很清楚你说的终止符具体是啥，流式响应是实现了的，在结束的时候会发送一个`[DONE]`

**Comment by shaoyuyoung** [comment]
好的，非常感谢 :)
